#!/bin/bash
#-----------------------------------------------------------------------------
# file: .rdrshell_plugins/hep
# author: Ryan Reece <ryan.reece@cern.ch>
# date : 2015-03-01
# -----------------------------------------------------------------------------

#-----------------------------------------------------------------------------
# condor
#-----------------------------------------------------------------------------
# condor_jobs()
# {
#     printf "%12s  %5s  %5s  %5s  %5s\n" "user" "jobs" "idle" "run" "other"
#     #   1     2 3          4 5        6   7     8   9      10 11   12 13        14
#     # 296 jobs; 0 completed, 0 removed, 176 idle, 120 running, 0 held, 0 suspended
#     all_results="all "
#     all_results+=$(condor_q | tail -1 | awk '{print $1" "$7" "$9" "$3+$5+$11+$13}')
#     printf "%12s  %5i  %5i  %5i  %5i\n" $all_results
#     ihavejobs=false
#     for u in $(condor_users)
#     do
#         user_results="$u "
#         user_results+=$(condor_q $u | tail -1 | awk '{print $1" "$7" "$9" "$3+$5+$11+$13}')
#         if [ "$u" = "$USER" ] ; then
#             n_my_condor_jobs=$(echo $user_results | awk '{print $2}')
#             n_my_condor_jobs_held=$(echo $user_results | awk '{print $5}')
#             if [ $n_my_condor_jobs_held -gt 0 ] ; then
#                 my_color=${LIGHTRED}
#             else
#                 my_color=${LIGHTCYAN}
#             fi
#             printf "${my_color}%12s  %5i  %5i  %5i  %5i\n${NC}" $user_results
#             ihavejobs=true
#         else
#             printf "%12s  %5i  %5i  %5i  %5i\n" $user_results
#         fi
#     done
#     if [ "$ihavejobs" = "false"  ] ; then
#         n_my_condor_jobs=0
#     fi
# }
# 
# condor_users()
# {
#     condor_q | tail -n+5 | head -n-2 | awk '{print $2}' | sort | uniq | sed ':a;N;$!ba;s/\n/ /g'
# }
# 
# condor_jobs_per_user()
# {
#     condor_q -r | tail -n+5 | awk '{print $2}' | sort | uniq -c 
# }
# 
# watch_condor_q()
# {
#     while true; do
#         echo `date`
#         condor_jobs
#         sleep 30
#     done
# }
# 
# watch_my_jobs()
# {
#     echo `date`
#     condor_jobs
#     while [[ $n_my_condor_jobs > 0 ]] ; do
#         sleep 30
#         echo `date`
#         condor_jobs
#     done
#     echo -e "${LIGHTGREEN}Your jobs have finished!${NC}"
# }
# 
# alias condor_me="condor_q -r ${USER}"
# alias condor_q_oldest="condor_q -r | head -20"
# alias condor_q_newest="condor_q -r | tail -20"
# 
# alias gf='grep fail */job*/*log'


#-----------------------------------------------------------------------------
# xrootd
#-----------------------------------------------------------------------------
xls()
{
    xrd $1 dirlist $2
#    xrd hn.at3f dirlist $1
#    xrd headprv dirlist $1
#    xrd nfsprv dirlist $1
}

gls()
{
    for word in `python -c "import glob; print ' '.join(sorted(glob.glob('$1/*')))"`
    do
        echo $word
    done
}


