#!/bin/bash
#-----------------------------------------------------------------------------
# file: .bash_env
# author: Ryan Reece <ryan.reece@cern.ch>
# date : 2010-06-21
# -----------------------------------------------------------------------------

#-----------------------------------------------------------------------------
# control
#-----------------------------------------------------------------------------
SETUP_GCC=true
SETUP_PYTHON=true
SETUP_ROOT=true
SETUP_PYQT=false
SETUP_NUMPY=false
SETUP_ORACLE=false


echo -ne "$LIGHTCYAN"


#-----------------------------------------------------------------------------
# UPenn
#-----------------------------------------------------------------------------
#export PENN_USER="rreece"
#
## ssh
#alias ssh_higgs="ssh ${PENN_USER}@higgs.hep.upenn.edu"
#alias ssh_dionysus="ssh ${PENN_USER}@dionysus.hep.upenn.edu"
#alias ssh_lxsrv02="ssh ${PENN_USER}@lxsrv02.hep.upenn.edu"
#alias ssh_ptklx="ssh ${PENN_USER}@ptklx.hep.upenn.edu"
#alias ssh_zeus="ssh ${PENN_USER}@zeus.hep.upenn.edu"
#alias ssh_pennt3="ssh ${PENN_USER}@at3i00.hep.upenn.edu"
#
## scp
#alias scp_zeus="scp -r ${PENN_USER}@zeus.hep.upenn.edu:"
#alias scp_dio="scp -r ${PENN_USER}@dionysus.hep.upenn.edu:"


#-----------------------------------------------------------------------------
# basic environment setup
#-----------------------------------------------------------------------------
case "$ME" in
    pennt3)
        echo "  - setupATLAS"
        echo -ne "${NC}"
        export ATLAS_LOCAL_ROOT_BASE="/opt/ATLASLocalRootBase"
        alias setupATLAS='source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh'
#        setupATLAS # not working, so...
        source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh
        echo -ne "$LIGHTCYAN"
    ;;
    *)
        true
    ;;
esac


#-----------------------------------------------------------------------------
# gcc
#-----------------------------------------------------------------------------
mysetup_gcc()
{
    case "$ME" in
        pennt3)
            echo "  - setting up gcc 4.32"
            localSetupGcc --gccVersion=gcc432_x86_64_slc5 --quiet
        ;;
        *)
            echo "  - not setting up gcc"
        ;;
    esac
}

if $SETUP_GCC ; then
    mysetup_gcc
fi


#-----------------------------------------------------------------------------
# python
#-----------------------------------------------------------------------------
mysetup_python()
{
    case "$ME" in
        pennt3)
            echo "  - setting up Python 2.6.5"
            localSetupPython --pythonVersion=2.6.5-x86_64-slc5-gcc43 --quiet
        ;;
        *)
            echo "  - not setting up python"
        ;;
    esac
}

if $SETUP_PYTHON ; then
    mysetup_python
fi


#-----------------------------------------------------------------------------
# ROOT and PyROOT
#-----------------------------------------------------------------------------
mysetup_root()
{
    do_setup_root=false
    case "$ME" in
        pennt3)
            echo "  - setting up ROOT 5.34.03"
            localSetupROOT --rootVersion=5.34.03-x86_64-slc5-gcc4.3 --skipConfirm --quiet
        ;;
        *)
        echo "  - not setting up root"
        ;;
    esac

    if [ $do_setup_root ]; then
        # if ROOTSYS is defined, setup the root paths
        export PATH=$ROOTSYS/bin:$PATH
        export LD_LIBRARY_PATH=$ROOTSYS/lib:$LD_LIBRARY_PATH
        export PYTHONPATH=$ROOTSYS/pyroot:$ROOTSYS/lib:$PYTHONPATH
    fi
}

if $SETUP_ROOT ; then
    mysetup_root
fi


#-----------------------------------------------------------------------------
# pyqt
#-----------------------------------------------------------------------------
mysetup_pyqt()
{
    case "$ME" in
        *)
            echo "  - not setting up PyQt"
        ;;
    esac
}

if $SETUP_PYQT ; then
    mysetup_pyqt
fi


#-----------------------------------------------------------------------------
# numpy and matplotlib
#-----------------------------------------------------------------------------
mysetup_numpy()
{
    case "$ME" in
        *)
            echo "  - not setting up numpy"
        ;;
    esac
}

if $SETUP_NUMPY ; then
    mysetup_numpy
fi


#-----------------------------------------------------------------------------
# castor
#-----------------------------------------------------------------------------
mysetup_castor()
{
    case "$ME" in
        afs)
#            export STAGE_SVCCLASS="atlcal"
            export STAGE_SVCCLASS="atldata"
#            export STAGE_SVCCLASS="atlascernuserdisk"
        ;;
        *)
            echo "  - not setting up CASTOR"
        ;;
    esac
}

if [ $ME = "afs" ]; then
    mysetup_castor
fi


#-----------------------------------------------------------------------------
# athena and grid tools setup
#-----------------------------------------------------------------------------
case "$ME" in
    pennt3)
        export AtlasSetup=/afs/cern.ch/atlas/software/dist/AtlasSetup
        alias asetup='source $AtlasSetup/scripts/asetup.sh'
        #alias setup_cmt="source /afs/cern.ch/sw/contrib/CMT/v1r20p20090520/mgr/setup.sh"
        alias setup_cmt="source /afs/cern.ch/sw/contrib/CMT/v1r21/mgr/setup.sh"
        alias setup_panda="source /afs/cern.ch/atlas/offline/external/GRID/DA/panda-client/latest/etc/panda/panda_setup.sh"
        #export PATHENA_GRID_SETUP_SH="/afs/cern.ch/project/gd/LCG-share/current/etc/profile.d/grid_env.sh"
        export PATHENA_GRID_SETUP_SH="/afs/cern.ch/project/gd/LCG-share/current_3.2/etc/profile.d/grid-env.sh"

        # dq2
        dq2-setup()
        {
            source /afs/cern.ch/project/gd/LCG-share/current/external/etc/profile.d/grid-env.sh
            sleep 1
            voms-proxy-init -voms atlas
            sleep 1
            source /afs/cern.ch/atlas/offline/external/GRID/ddm/DQ2Clients/setup.sh
        }
    ;;
    *)
        true
    ;;
esac


#-----------------------------------------------------------------------------
# xrootd
#-----------------------------------------------------------------------------
# case "$ME" in
#     pennt3)
#         xls()
#         {
#             xrd hn.at3f dirlist $1
#         }
#     ;;
#     ucsct3)
#         xls-headprv()
#         {
#             xrd headprv dirlist $1
#         }
#         xls-nfsprv()
#         {
#             xrd nfsprv dirlist $1
#         }
#     ;;
# esac


#-----------------------------------------------------------------------------
# oracle
#-----------------------------------------------------------------------------
mysetup_oracle()
{
    case "$ME" in
        *)
            echo "  - not setting up oracle"
        ;;
    esac
}

if $SETUP_ORACLE ; then
    mysetup_oracle
fi


#-----------------------------------------------------------------------------
# yaml
#-----------------------------------------------------------------------------
if [ $ME = "pennt3" ]; then
    echo "  - setting up PyYAML"
    export PYTHONPATH=/usr/local/lib/python2.6/site-packages:$PYTHONPATH
fi


#-----------------------------------------------------------------------------
# guarantee back to no-color
echo -ne "$NC"


# EOF
