#!/bin/bash
#-----------------------------------------------------------------------------
# author: Ryan Reece <ryan.reece@cern.ch>
# date : 2014-06-21
# -----------------------------------------------------------------------------

if [ -f /etc/bashrc_t3 ]; then
    source /etc/bashrc_t3
fi


#-----------------------------------------------------------------------------
# UCSC
#-----------------------------------------------------------------------------
#export UCSC_USER="reece"
#export PFLOCK_QUEUE="/export/share/data/public/pflock/cp2"
#
#export UCSC_DESKTOP_IP="128.114.130.117"
#alias ssh_ucsc_desk="ssh ${UCSC_USER}@${UCSC_DESKTOP_IP}"
#
#
#alias ssh_ucsct3="ssh ${UCSC_USER}@atlas02.ucsc.edu"
#alias t3="ssh ${UCSC_USER}@atlas02.ucsc.edu"
#alias t3x="ssh -X ${UCSC_USER}@atlas02.ucsc.edu"
#alias ssh_atlas01="ssh ${UCSC_USER}@atlas01.ucsc.edu"
#alias ssh_atlas02="ssh ${UCSC_USER}@atlas02.ucsc.edu"
#alias ssh_atlas03="ssh ${UCSC_USER}@atlas03.ucsc.edu"
#alias ssh_atlas04="ssh ${UCSC_USER}@atlas04.ucsc.edu"
#alias ssh_ucsc_web="ssh ${UCSC_USER}@reece.scipp.ucsc.edu"


#-----------------------------------------------------------------------------
# tossing files (MY_TOSS_INBOX)
#-----------------------------------------------------------------------------
toss_ucsc_web()
{
    for f in "${@%/}"
    do
        rsync -ahC -i $f ${UCSC_USER}@reece.scipp.ucsc.edu:share/inbox/
#        scp -r $f ${UCSC_USER}@reece.scipp.ucsc.edu:html/share/inbox/
    done

}

alias share="toss_ucsc_web"


#-----------------------------------------------------------------------------
# MY_SHARE_DIR
#-----------------------------------------------------------------------------
#case "$ME" in
#    afs)
#        export MY_SHARE_DIR="/afs/cern.ch/user/r/${CERN_USER}/www/share/"
#    ;;
#    pennt3)
#        export MY_SHARE_DIR="/web/Analysis/${CERN_USER}/share/"
#    ;;
#    ucsct3)
#        export MY_SHARE_DIR="reece.scipp.ucsc.edu:share/"
#    ;;
#    ubuntu)
#        case "$HOSTNAME" in
#            descartes)
#                export MY_SHARE_DIR="/var/www/share"
#            ;;
#            *)
#                export MY_SHARE_DIR="lxplus.cern.ch:www/share/"
#            ;;
#        esac
#    ;;
#    *)
#        export MY_SHARE_DIR="${CERN_USER}@lxplus.cern.ch:www/share/"
#    ;;
#esac

## share
#share()
#{
#    for f in "$@"
#    do
#        cp -rf $f ${MY_SHARE_DIR}
#    done
#}


